permissions:
  contents: write
  packages: write
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Version"
      name:
        type: string
        required: false
        description: "Title"
        default: ""
      description:
        type: string
        required: true
        description: "Description of changes"

env:
  ARTIFACT_NAME: ResoniteLogCleaner
name: "Create Release"
jobs:
  check-inputs:
    runs-on: ubuntu-latest
    steps:
    - name: "Check version format"
      env:
        RELEASE_VERSION: "${{ inputs.version }}"
      shell: bash
      run: |
        # https://semver.org/ applied to https://stackoverflow.com/questions/21112707/check-if-a-string-matches-a-regex-in-bash-script
        [[ "$RELEASE_VERSION" =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]

  compile:
    uses: ./.github/workflows/build.yml
    needs: check-inputs
    with:
      RELEASE_VERSION: "${{ inputs.version }}"
      RELEASE_NOTES: "${{ inputs.description }}"

  create-github-release:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: "${{ env.ARTIFACT_NAME }}"
        path: "tmp/"
    - name: Pack artifacts
      run: zip ${{ env.ARTIFACT_NAME }}.zip ${{ env.ARTIFACT_NAME }}.*
      working-directory: "tmp/"
    - name: Create release
      uses: "ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5"
      with:
        artifactErrorsFailBuild: true
        artifacts: "tmp/${{ env.ARTIFACT_NAME }}.zip"
        body: "${{ inputs.description }}"
        name: "${{ inputs.name || inputs.version }}"
        tag: "v${{ inputs.version }}"
        commit: "${{ github.ref }}"